### ISSUE TITLE
Add method to format a single CSLItemData

### ISSUE THREAD

**Issue by mdoering** [michel-kraemer/citeproc-java#104]
I often need to format a single citation without being part of a full bibliography. It would be great if there would be a thread safe CSL method like CSL.formatEntry(CSLItemData) that returns a String just as the entry in a full bibliography, but without the need to register it and have the ItemDataProvider know about it.

**Comment by michel-kraemer** [comment]
I've added a static method to generate ad-hoc citations (`makeAdhocCitation`). For bibliographies, there already is a static method called `makeAdhocBibliography`.
