### ISSUE TITLE
Editor missing from dataset version in APA style

### ISSUE THREAD

**Issue by mdoering** [michel-kraemer/citeproc-java#106]
When I render the bibliography for the following CSL-JSON 
```
{"id":"-GEN-2nsfj8k4n8","type":"dataset","author":[{"family":"Andrella","given":"Giovani Carlos"},{"family":"Atahuachi Burgos","given":"Margoth"}],"editor":[{"family":"Govaerts","given":"Rafaël"}],"accessed":{"dateParts":[[1999]]},"issued":{"dateParts":[[2021,5,16]]},"DOI":"10.1093/database/baw125","ISSN":"1758-0463","title":"The World Checklist of Vascular Plants (WCVP): Fabaceae","URL":"gbif.org","version":"1.0"}
```

with the [7th APA style from Zotero](https://github.com/michel-kraemer/citeproc-java/files/6709883/apa.csl.zip)
using Frank Bennetts citeproc-js v1.4.61 I yield:

>   Andrella, G. C., &#38; Atahuachi Burgos, M. <i>The World Checklist of Vascular Plants (WCVP): Fabaceae</i> (R. Govaerts, Ed.; 1.0) [Data set]. https://doi.org/10.1093/database/baw125

When I do the same with the latest v3 snapshot from citeproc-java it looks rather different. The editor is entirely missing and there is now an issued date:

> Andrella, G. C., &amp; Atahuachi Burgos, M. (2021). <i>The World Checklist of Vascular Plants (WCVP): Fabaceae</i> (1.0). https://doi.org/10.1093/database/baw125

See also #102 for wrong `eds.` placement.

**Comment by michel-kraemer** [comment]
Thanks for reporting this issue and for the example JSON. This made it really easy to reproduce the bug. :+1:

I fixed the issue in the latest snapshot. Same applies to #102 by the way.

**Comment by michel-kraemer** [comment]
Oh, one more thing: your JSON contains the attribute `dateParts`, which is invalid. The correct name should be `date-parts`. That's the reason why citeproc-js doesn't show the issued date.

Where does this JSON come from? Has it been generated by citeproc-java? If yes, that's another bug we need to fix. I'd be happy if you could confirm (or not confirm) that.

**Comment by mdoering** [comment]
great! And thanks for the `date-parts` spotting, I overlooked that.
