### ISSUE TITLE
No Date (n.d.) missing

### ISSUE THREAD

**Issue by mdoering** [michel-kraemer/citeproc-java#109]
When using the 7th APA style with CSL data that does not contain any `issued` date, n.d. should be rendered instead of the year in a bibliography. citeproc-js does this, but the latest citeproc-java snapshot does simply leave out any date:

citeproc-js:
> Bánki, O., Roskov, Y., Vandepitte, L., DeWalt, R. E., Remsen, D., Schalk, P., Orrell, T., Keping, M., & Miller, J. (n.d.). Catalogue of Life Checklist (Y. Roskov, Ed.; working draft) [Data set]. Catalogue of Life.

citeproc-java:
> Bánki, O., Roskov, Y., Vandepitte, L., DeWalt, R. E., Remsen, D., Schalk, P., Orrell, T., Keping, M., & Miller, J. Catalogue of Life Checklist (working draft) [Data set]. Catalogue of Life.

**Comment by michel-kraemer** [comment]
This issue is now fixed in citeproc-java v3.0.0-alpha.3
