### ISSUE TITLE
How does JS-Execution work without underlying html?

### ISSUE THREAD

**Issue by Osiris-Team** [michel-kraemer/citeproc-java#110]
What about this?
```javascript
document.someMethod()
```

**Comment by michel-kraemer** [comment]
I'm not sure if I understand the question. Can you please elaborate?

**Comment by Osiris-Team** [comment]
@michel-kraemer I think javascript is mostly used on websites. Normally the code is inside a `<script>` block and you are able to modify the HTML DOM with it. So how can I do that with the citeproc api?

**Comment by michel-kraemer** [comment]
citeproc-java is a Java library. It runs on the JVM. Up to version 14, the JDK has been shipped with a JavaScript interpreter (Nashorn). In JDK 15, this interpreter was removed. The upcoming citeproc-java 2.0 will therefore not use JavaScript anymore. An alpha version with a pure-Java CSL interpreter is already available (https://search.maven.org/artifact/de.undercouch/citeproc-java/3.0.0-alpha.2/jar).

I hope this helps. Let me know if this answers your question and please close the issue if it does. Thanks.

**Comment by Osiris-Team** [comment]
Ok guess I completly missunderstood the purpose of this library. Thanks for clarifying.
