### ISSUE TITLE
Changes to apa.csl - missing initial for the first name of firstauthor

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#112]
Hello Michel, thank you for your help.

I'm from ExLibris, specifically in Primo discovery solutions for academic libraries.
I'd like to approach you with a question concerning recent changes done to apa.csl file as we got many cases from our customers complaining on missing first initial of a first name of the first author. 

We have recently update Primo to use the recent apa.csl and as soon as we did this , we saw the following citation generated for apa.csl :
As you can see below for the first author, we are missing the initial of the first name , for the other authors we do see the first name of author name 

Is this an expected behavior?  Can you please advise how we should proceed - we have many customers complaining on this issue  ?

![image](https://user-images.githubusercontent.com/63962951/145039582-1e65f748-65fc-4fc4-8f94-5db124b3261b.png)

 
List of author for this record:
 
![image](https://user-images.githubusercontent.com/63962951/145039620-a06c8d30-f5a4-4ee7-b4a6-0b678d404a4f.png)

Comparing to APA 6th edition : the first initial of the first author's name appears  
 
![image](https://user-images.githubusercontent.com/63962951/145039658-1f65bc67-7793-47a7-bfe1-bf8e105a9327.png)

We wanted to check with you if this change is related to the "Update APA disambiguation rules to only initials" change that was committed recently.
 
![image](https://user-images.githubusercontent.com/63962951/145039678-f4bbc522-36e3-41fb-99d0-d61004031e18.png)

Following your response below we have upgraded our version to use the following dependencies as you recommended and still we see that for apa.csl is still dropping the is dropping first author name

we do send as shown below the data with the full author names.

<dependency>
<groupId>de.undercouch</groupId>
<artifactId>citeproc-java</artifactId>
<version>3.0.0-alpha.2</version>
</dependency>

Also pulling the following snapshots from styles 
<dependency> <groupId>org.citationstyles</groupId>
<artifactId>styles</artifactId>
<version>21.10-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>org.citationstyles</groupId>
<artifactId>locales</artifactId>
<version>21.10-SNAPSHOT</version>
</dependency>

Below you can find the data that Primo sends to the citeproc to generate the citation – Primo sends the author's full name and apa.csl style is dropping the first author name 
 
![image](https://user-images.githubusercontent.com/63962951/145039757-c4106cb8-20c5-4528-8a5f-fa8d6a6a596d.png)

This is the apa citation output:
        “Hillyer, Hofbauer, Germaine A, United States. Army. Corps of Engineers, & Water Resources Support Center. (1998). Water supply handbook a handbook on water supply planning and resource management (Rev..). U.S. Army Corps of Engineers, Water Resources Support Center, Institute for Water Resources.

And this is the csl object:
```json
{
   "id":"-GEN-1krfv1gpea",
   "type":"book",
   "language":"en-US",
   "author":[
      {
         "family":"Hillyer",
         "given":"Theodore M."
      },
      {
         "family":"Hofbauer, Germaine A",
         "given":""
      },
      {
         "family":"United States. Army. Corps of Engineers",
         "given":""
      },
      {
         "family":"Water Resources Support Center",
         "given":""
      }
   ],
   "issued":{
      "date-parts":[
         [
            1998
         ]
      ]
   },
   "container-title":"",
   "DOI":"",
   "edition":"Rev..",
   "ISBN":"1234567101",
   "ISSN":"",
   "issue":"",
   "keyword":"Water-supply -- United States -- Management; Water-supply -- United States -- Planning",
   "note":"",
   "number-of-pages":"",
   "page":"",
   "page-first":"",
   "PMID":"",
   "publisher":"U.S. Army Corps of Engineers, Water Resources Support Center, Institute for Water Resources",
   "publisher-place":"Alexandria, VA",
   "section":"",
   "title":"Water supply handbook a handbook on water supply planning and resource management",
   "URL":"",
   "volume":""
}
```

**Comment by michel-kraemer** [comment]
Thanks for getting in touch. I tried to reproduce the issue with citeproc-java 3.0.0-alpha.2 and `org.citationstyles:styles:21.11` but it seems everything works as expected. I created a small test project here:
https://github.com/michel-kraemer/citeproc-java-issue-112

The code correctly prints the following:

Hillyer, T. M., Hofbauer, Germaine A, United States. Army. Corps of Engineers, &amp; Water Resources Support Center. (1998). _Water supply handbook a handbook on water supply planning and resource management_ (Rev..). U.S. Army Corps of Engineers, Water Resources Support Center, Institute for Water Resources.

Please have a look at the test code and compare it with yours. Let me know if this fixes your problem. If not, please modify the test code so that I can reproduce the issue. Thanks!

**Comment by PrimoQA** [comment]
Thank you very much for your effort! it worked :)
We changed to the version 3.0.0-alpha.2 and used the following code instead of CSL.makeAdhocBibliography, and got the initials as expected:

			ListItemDataProvider itemDataProvider = new ListItemDataProvider(new ArrayList<CSLItemData>(Arrays.asList(data)));
			CSL itemDataProviderCSL = new CSL(itemDataProvider, style);
			itemDataProviderCSL.registerCitationItems(itemDataProvider.getIds());
			return makeCslResponse(itemDataProviderCSL.makeBibliography());
			
After we changed the code and version (to 3.0.0-alpha.2), we noticed new issues in the citation, are they known?

1. Once issue info is missing, empty parentheses are displayed near volume info.
    example (see empty parentheses after 277): 
Flagiello, D., Di Natale, F., Erto, A., & Lancia, A. (2020). Wet oxidation scrubbing (WOS) for flue-gas desulphurization using sodium chlorite seawater solutions. Fuel (Guildford), 277(), 118055. https://doi.org/10.1016/j.fuel.2020.118055

2. each citation has 'https://doi.org/' component as a part of it, even when no DOI is part of a data set for the checked record.
    example (See https://doi.org/ at the end) Banville, J., & O'Malley, W. T. (2005). The sea. In (1st American ed..). Knopf : Distributed by Random House. https://doi.org/

3. In case where autors names are missing initials and only displayed with a last name,  APA CSL citation is structured with doubled commas.
     example (see , ,): 
Kasam, , Yulianto, , Saepudin, , & Prabowo, G. G. (2020). Mapping the Strength of Research in the Focus Areas for Transportation based on SCOPUS 2014 - 2018. IOP Conference Series. Earth and Environmental Science, 448(1), 12107. https://doi.org/10.1088/1755-1315/448/1/012107

4. It seems that if a volume info is not a part of a citation, issue and pages info are displayed in parentheses with with a comma at the beginning
    example see  (, p. 435): 
New Economic Development Research Has Been Reported by Researchers at Cracow University of Economics (Exploring concomitant concepts in the discussion on the circular economy: A bibliometric analysis of Web of Science, Scopus and Twitter). (2021). In Economics Week (, p. 435). NewsRX LLC. https://doi.org/


Thank you for your help!

**Comment by michel-kraemer** [comment]
Please replace empty strings with `null` in your CSL object. This should solve all issues you see.
