### ISSUE TITLE
Number field missing in Jabref entry preview for APA 7th and 6th edition

### ISSUE THREAD

**Issue by ThiloteE** [michel-kraemer/citeproc-java#113]
Hello Michel,

the corresponding discussion and information about how to reproduce as well as the likely identification of the underlying code changes that led to this behaviour can be found here:

https://github.com/JabRef/jabref/issues/8372

**Comment by michel-kraemer** [comment]
Thanks for the link to the discussion! Please see my reply here:
https://github.com/JabRef/jabref/issues/8372#issuecomment-1003526104

**Comment by ThiloteE** [comment]
People at Jabref are still working on it. Just posting here to prevent this issue from being closed.

**Comment by ThiloteE** [comment]
We finally fixed this issue here downstream via https://github.com/JabRef/jabref/pull/8607. Thank you Michel. Your initial proposed solution helped a lot!

We went with the following mapping:

|BibTeX|BibLaTeX|CSL| proposed logic, conditions and info |
|:---|:---|:---|:----|
| volume | volume | volume | |
| number | issue     | issue  | For conversion to CSL or BibTeX: BibLaTeX `number` takes priority and supersedes BibLaTeX `issue`|
| number | number | issue | For conversion to CSL or BibTeX: BibLaTeX `number` takes priority and supersedes BibLaTeX `issue`|
| pages | eid | [number](https://docs.citationstyles.org/en/stable/specification.html#number-variables) | Some journals put the article-number (= eid) into the pages field. If BibLaTeX `eid` exists, map to csl `number` and provide this to the style. If `pages` exists, map to csl `page`.  If `eid` WITHIN the `pages` field exists, detect the eid and map to csl `number`. If both `eid` and `pages` exists, ideally map to both csl `number` and csl `page` respectively and provide this to the style. Ideally the citationstyle should be able to flexibly choose the rendering. If this is not possible then map biblatex `eid` to CSL `page`, since this is sufficient to comply with APA 7th edition, but will break other citationstyles (e.g. IEEE)|
| pages | pages | page | "" |
