### ISSUE TITLE
Some name variables missing?

### ISSUE THREAD

**Issue by ebergasa** [michel-kraemer/citeproc-java#137]
Hello Michel,
We have found that there are some missing methods to be able to set some `Name Variables` that are part of [CSL specification](https://docs.citationstyles.org/en/stable/specification.html#name-variables):

```
chair
compiler
contributor
curator
editor-translator
executive-producer
guest
narrator
organizer
performer
producer
script-writer
series-creator
```

Is this intentionally done? Or just because you started by implementing the more used/useful fields?

Will you evaluate some of them to be included? We find that at least `compiler`, `contributor`, `chair` and `organizer` are important.

Thanks for listening, and for your work!!

**Comment by michel-kraemer** [comment]
I'm not sure. This was probably just an oversight on my part. Thanks for reporting this!
