### ISSUE TITLE
harvard-imperial-college-london style: extra space is displayed between initials of author's name

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#151]
Describe the bug:
There are extra spaces between initials in authors' names.

Which version of citeproc-java are you using?
1.0.1
Expected behavior
There should not be an extra space between initials in author's name, such as :
Chen, B.-Y. & Janes, H.W. (2002) PCR Cloning Protocols. Second Edition. [Online]. Totowa, Humana Press. Available from: doi:10.1385/1592591779.

Actual behavior
In a citation below there is an extra space between author's initials:
Chen, B.-Y. & Janes, H. W. (2002) PCR Cloning Protocols. Second Edition. Humana Press. doi:10.1385/1592591779.

CSL input:
If applicable, add the input to citeproc-java (i.e. the CSL citation data in JSON)
CSL api object fields: {"id":"-GEN-d2cobcl8v","type":"book","language":"eng","author":[{"family":"Chen","given":"Bing-Yuan"},{"family":"Janes","given":"Harry W"}],"issued":{"date-parts":[[2002]]},"container-title":"","DOI":"10.1385\/1592591779","edition":"Second Edition.","ISBN":"0896039692","ISSN":"","issue":"","keyword":"Biochemistry ; Biochemistry, general ; Cell Biology ; Cytology ; Laboratory manuals ; Molecular cloning ; Polymerase chain reaction ; Science, Humanities and Social Sciences, multidisciplinary","note":"","number-of-pages":"455","page":"","page-first":"","PMID":"","publisher":"Humana Press","publisher-place":"Totowa","section":"","title":"PCR Cloning Protocols","URL":"","volume":"192"}
Used style and locale
harvard-imperial-college-london

Rendered output/Screenshots
If applicable, add the output that citeproc-java produced and/or screenshots to help explain your problem.
Example code/unit test
Provide example code or a unit test to reproduce your issue. You may also insert a link to your repository containing a minimal reproducer here.

**Comment by michel-kraemer** [comment]
I cannot reproduce this with the latest version 3.0.0-alpha.6. Please update and try again.
