### ISSUE TITLE
IEEE citation style: journal's title is displayed in full instead of being abbreviated

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#153]
**Describe the bug**
Article is cited --> a title of a journal the cited article belongs to is displayed in full as a part of a citation/ within the version 3.0.0-alpha.2., while it should be abbreviated.

Please fill in the following sections and provide as much information as possible. It will help us to reproduce the issue. Leave sections blank or remove them if they don't apply.

**Which version of citeproc-java are you using?**
1.0.1

Let us know which citeproc-java version you are using exactly so we can reproduce the issue.

**Expected behavior**
[1]
R. Hisakata, S. Nishida, and A. Johnston, “An adaptable metric shapes perceptual space,” Curr. Biol., vol. 26, no. 14, pp. 1911–1915, Jul. 2016, doi: 10.1016/j.cub.2016.05.047.

**Actual behavior**
[1]R. Hisakata, S. Nishida, and A. Johnston, “An Adaptable Metric Shapes Perceptual Space,” Current biology, vol. 26, no. 14, pp. 1911–1915, 2016, doi: 10.1016/j.cub.2016.05.047.
Note the incorrect numbering as well.

**CSL input**
 CSL api object fields: {"id":"-GEN-13j66mi466","type":"article-journal","language":"eng","author":[{"family":"Hisakata","given":"Rumi"},{"family":"Nishida","given":"Shin&#8217;ya"},{"family":"Johnston","given":"Alan"}],"issued":{"date-parts":[[2016]]},"container-title":"Current biology","DOI":"10.1016\/j.cub.2016.05.047","edition":"","ISBN":"","ISSN":"0960-9822","issue":"14","keyword":"Adaptation, Physiological ; Form Perception ; Humans ; Motion Perception ; Photic Stimulation ; Report ; Retina - physiology","note":"","number-of-pages":"","page":"1911-1915","page-first":"1911-1915","PMID":"27426520","publisher":"Elsevier Ltd","publisher-place":"England","section":"","title":"An Adaptable Metric Shapes Perceptual Space","URL":"","volume":"26"}

**Used style and locale**
IEEE

**Comment by michel-kraemer** [comment]
Thanks for reporting this. Abbreviations are not supported at the moment but I'm working on it. Can you please let me know how you configured abbreviations? Did you set a short container title somewhere in your CSL input? Or did you pass an `AbbreviationProvider` to the constructor of the `CSL` class? Maybe you can provide a short code example demonstrating the issue?
