### ISSUE TITLE
Support of 'name-part' attributes in version 3.0

### ISSUE THREAD

**Issue by alaxos** [michel-kraemer/citeproc-java#177]
Hi Michel,

I'm using the 3.0.0-alpha.7 and I noticed that the `name-part` attributes seem to be ignored (for instance the `text-case="uppercase"` part in the example below). And it looks to me that the code actually doesn't support it.

    <name and="text" name-as-sort-order="all" sort-separator=", " delimiter=", " delimiter-precedes-last="never">
      <name-part name="family" text-case="uppercase"/>
      <name-part name="given"/>
    </name>

Am I right or am I missing something ? If not, do you have any plan to support it ?

Generally speaking, we are planning to use your code in production in a few months and generally speaking I would like to know if you already have any idea of a release date for the 1st stable version?

In any case, thank you very much for your much appreciated work!
Nicolas

**Comment by michel-kraemer** [comment]
Thank you for reporting this! The issue should now be fixed.

> I would like to know if you already have any idea of a release date for the 1st stable version?

Currently, there is no fixed timeline yet. However, I consider the current alpha version quite stable already. Some aspects of the CSL specification haven't been implemented yet, but in general it should work quite well and using it in production shouldn't be a problem. Before I can release the new version I still need to update the website. I haven't found time for that yet, but I will certainly do it in the near future.

**Comment by alaxos** [comment]
Hi Michel,

I was waiting for an answer and I got an answer, a commit and a new release! The only thing I can say is a huge thank you!

And thank you for the clarifications for the stability. Once again, thank you very much for your great work.
