### ISSUE TITLE
CSL.getSupportedStyles() returns null

### ISSUE THREAD

**Issue by arpit1984** [michel-kraemer/citeproc-java#191]
I am trying to pull all the supported csls using CSL.getSupportedStyles(); and it works fine on my local and dev version.
Though, I am building the application to create a war to deploy it on server, it throws the following error:
java.io.FileNotFoundException: /home/tomcat/appname/appname.war!/WEB-INF/lib/styles-23.1.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at de.undercouch.citeproc.CSL.getAvailableFiles(CSL.java:329)
        at de.undercouch.citeproc.CSL.getSupportedStyles(CSL.java:352)

I read that the styles should be on classpath. How do i that? Becauase it works fine on local version but fails when I build the war file

**Comment by michel-kraemer** [comment]
This is probably fixable. Can you please have a look at the contents of your war file and let me know if there is a `styles-23.1.jar` file inside the war file (like it says in the error message) or if you can find the style files (with the extension `.csl`) in the root directory of the war file? This would help a lot. Thanks.

**Comment by arpit1984** [comment]
yes, I see the styles-23-.jar1file in WEB-INF/lib. So, I think the way I am creating the war file, it is not able to read the zip files inside it.

**Comment by michel-kraemer** [comment]
🤔 OK. So, it's a jar file inside a war file. That might be a bit hard to implement. Here's the code of the `getSupportedStyles()` method:
https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/main/java/de/undercouch/citeproc/CSL.java#L289-L291
and more importantly the `getAvailableFiles()` method:
https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/main/java/de/undercouch/citeproc/CSL.java#L248-L282

Maybe you can figure out yourself how to fix the issue or let me know what I can do. I'd be more than happy to help you and implement a fix but I need a sensible approach. Let me know if you have an idea. Pull requests are also welcome, of course.

**Comment by michel-kraemer** [comment]
After you've cloned the repository, you need to run `./gradlew generateSources` to generate the missing class files. The locales and styles are in a separate repository:
https://github.com/michel-kraemer/citationstyles-snapshot-updater/

**Comment by lezhan** [comment]
Hello @michel-kraemer. I have the same problem jar in jar.

**Comment by michel-kraemer** [comment]
@lezhan Wow! Very cool. Thank you! Maybe the part with the three nested while loops can be simplified a bit, but I guess the trick here is the `resolveUrl` method and to use `ZipInputStream` instead of `ZipFile`, isn't? I will try to integrate this into citeproc-java and get back to you.

**Comment by michel-kraemer** [comment]
Thanks for the support! I've published a new version 3.0.0-beta.2. Please try again and let me know if the problem persists.

**Comment by lezhan** [comment]
@michel-kraemer 
yes, you are right the trick is the resolveUrl method and ZipInputStream. I have tested it, everything works correct. Thank you for such a great app :-).
