### ISSUE TITLE
citeproc-java is very slow for more than 400 references

### ISSUE THREAD

**Issue by arpit1984** [michel-kraemer/citeproc-java#196]
I am using the standalone executable "citeproc-java" on unix machine. I am using following command to generate the citations in ieee style. 
./citeproc-java bibliography -i ~/10_254b477f-f650-4030-81cd-ec0ecd32c22a.ris -f text

The ris file has more than 400 references and its been more than 20 minutes with no results but I see it is consuming more than 50G of memory. Is there any limits or recommended limit that should be used with this tool?
Also, all i need just citations(string text) in certain style. What will you recommend.

**Comment by michel-kraemer** [comment]
Which version of the `citeproc-java` tool are you using? Have you compiled it yourself from the repository you cloned? If not, please try to do that. citeproc-java 3.0.0-beta.1 is considerably faster than citeproc-java 2.

**Comment by arpit1984** [comment]
I was using one the binary which is provided in this link https://michel-kraemer.github.io/citeproc-java/download/ 
Also, I am running it on java8. I read somewhere that java 11 might be faster as it has some different enginer. I might be wrong

**Comment by michel-kraemer** [comment]
This is the citeproc-java 2. As I said, if you've already cloned the repository (I assume this is true from the other thread), then please build the tool yourself with `./gradlew installDist`. You'll find the tool under `build/distributions`.

**Comment by arpit1984** [comment]
Thanks. I am trying to build it on unix using your suggested command but I am getting following error:

> * Where:
> Build file '/home/arpit.tandon/citeproc-java/citeproc-java/build.gradle' line: 37
> 
> * What went wrong:
> Execution failed for task ':citeproc-java:generateSources'.
> > org/eclipse/core/runtime/Plugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by arpit1984** [comment]
I upgraded my JAVA JDK to 19 and ran the ./gradlew installDist. It says it built succesfully, but I dont see the any folder "distributions" anywhere

**Comment by arpit1984** [comment]
found it and it works like charm. Much much much faster
