### ISSUE TITLE
CSLType enum do not contain some types exist in official documentation

### ISSUE THREAD

**Issue by lezhan** [michel-kraemer/citeproc-java#199]
**Describe the bug**
CSLType enum do not contain some types exist in official documentation https://docs.citationstyles.org/en/stable/specification.html#appendix-iii-types
DOCUMENT, PERIODICAL, SOFTWARE, STANDARD

**Existed types:**
public enum CSLType {
    ARTICLE("article"),
    ARTICLE_JOURNAL("article-journal"),
    ARTICLE_MAGAZINE("article-magazine"),
    ARTICLE_NEWSPAPER("article-newspaper"),
    BILL("bill"),
    BOOK("book"),
    BROADCAST("broadcast"),
    CHAPTER("chapter"),
    DATASET("dataset"),
    ENTRY("entry"),
    ENTRY_DICTIONARY("entry-dictionary"),
    ENTRY_ENCYCLOPEDIA("entry-encyclopedia"),
    FIGURE("figure"),
    GRAPHIC("graphic"),
    INTERVIEW("interview"),
    LEGAL_CASE("legal_case"),
    LEGISLATION("legislation"),
    MANUSCRIPT("manuscript"),
    MAP("map"),
    MOTION_PICTURE("motion_picture"),
    MUSICAL_SCORE("musical_score"),
    PAMPHLET("pamphlet"),
    PAPER_CONFERENCE("paper-conference"),
    PATENT("patent"),
    PERSONAL_COMMUNICATION("personal_communication"),
    POST("post"),
    POST_WEBLOG("post-weblog"),
    REPORT("report"),
    REVIEW("review"),
    REVIEW_BOOK("review-book"),
    SONG("song"),
    SPEECH("speech"),
    THESIS("thesis"),
    TREATY("treaty"),
    WEBPAGE("webpage");

**Which version of citeproc-java are you using?**
3.0.0-beta.2

**Comment by michel-kraemer** [comment]
Thanks for spotting this!
