### ISSUE TITLE
Line break in BibTeX title causes incorrect rendering of special characters

### ISSUE THREAD

**Issue by apurde** [michel-kraemer/citeproc-java#23]
While the official 0.6 release is not able to deal with a line break in the BibTeX title the current sources are. However the line break causes some rendering issues of special characters and escaped characters. I don't know whether line breaks in the title should be rated as valid and whether this is an issue of citeproc-java but I wanted to record it here anyhow.

Thank you,

Andreas

Artificial example:

@article{Issue09,
  author = "Jo{\"e}l Biran{\c c}on and Philippe Maisonobe and Michel Merle",
   title = "Localisation de syst`emes
   diff\'erentiels, stratifications de {W}hitney et condition de {T}hom",
 journal = "Invent. Math.",
  volume = 66,
    year = 1990,
   pages = "12--16"}

results in the following text output:

J. Birancon, P. Maisonobe, and M. Merle, “Localisation de syst`emes diff’erentiels, stratifications de {W}hitney et condition de {T}hom,” Invent. Math., vol. 66, pp. 12–16, 1990.

while

@article{Issue09,
  author = "Jo{\"e}l Biran{\c c}on and Philippe Maisonobe and Michel Merle",
   title = "Localisation de syst`emes diff\'erentiels, stratifications de {W}hitney et condition de {T}hom",
 journal = "Invent. Math.",
  volume = 66,
    year = 1990,
   pages = "12--16"}

results in the correct output:

J. Birancon, P. Maisonobe, and M. Merle, “Localisation de systèmes différentiels, stratifications de Whitney et condition de Thom,” Invent. Math., vol. 66, pp. 12–16, 1990.

**Comment by michel-kraemer** [comment]
I cannot reproduce this with the latest snapshot:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/1.0.0-SNAPSHOT/

Could you please give me more information (e.g. which CSL style you used, etc.)? It would be perfect if you could provide a small example program (maybe a Gist) demonstrating the issue, so I can reproduce it. Thanks!

Michel

**Comment by michel-kraemer** [comment]
I just published version 1.0.0 which should solve the issue. If you still have problems feel free to open the issue again.

Cheers,
Michel

**Comment by apurde** [comment]
Dear Michel,

thank you for providing the new version. I just updated my plugin but the error is still there. I use ieee as output format.

Kind regards,

Andreas

**Comment by apurde** [comment]
To make it easier: https://bitbucket.org/apurde/simple-cite/downloads/Issue09.bib contains two cites. "ok" renders well, "nok" shows the mentioned problem.

**Comment by michel-kraemer** [comment]
Thanks for the bib file. I can now reproduce the problem. I'll try to fix it and get back to you.

**Comment by michel-kraemer** [comment]
I fixed the problem. Please try again with version 1.0.1 that will be released in a couple of minutes.

**Comment by apurde** [comment]
Dear Michel,

I can confirm it is closed.

Thank you for your effort, Andreas
