### ISSUE TITLE
Source code : Build failed 

### ISSUE THREAD

**Issue by gduh** [michel-kraemer/citeproc-java#25]
Hi,

I try to build a new jar from the source code. The aim is to change the dependency version for jBibText.

But when I try to build the project without any change in it, I get an exception : 

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xxxx/Downloads/citeproc-java-0.6 2/build.gradle' line: 70

* What went wrong:
Execution failed for task ':generateSources'.
> Index: 0, Size: 0

I don't usually used Gradle so I don't known how to solve the problem.
Thanks for your help.

**Comment by apurde** [comment]
The same happend to me for the official 0.6 sources. The newest ones from Git worked with excluding test and doc build. There was obviously a major update in grade.

Andreas

**Comment by gduh** [comment]
Thanks for your quick answer, but how do you exclude test and doc build ?

**Comment by apurde** [comment]
Sorry I can't remember. Something like adding "-x test -x doc"...

**Comment by gduh** [comment]
It's ok now with "-x test" (doc not exists) and the newest sources.

**Comment by michel-kraemer** [comment]
Thanks for letting me know. I will try to release a new version soon so that these problems should go away. I'll close this issue for now.

**Comment by gduh** [comment]
Finally, I always use cite-proc but without JBibTeX since I have a lot of problems with specials characters. 
So I do not use bibteX files but JSON. It's more complicated for me, but I don't find anything else.
