### ISSUE TITLE
Formatting with China GB7714

### ISSUE THREAD

**Issue by hongjingxu** [michel-kraemer/citeproc-java#250]
Hi Michel,

Many thanks for your project.
I am trying to generate the bibliography following "china-national-standard-gb-t-7714-2015-numeric" for below CSL-JSON:
	{
		"id": "GXNGXXQN",
		"type": "article-journal",
		"container-title": "International Journal of Toxicology",
		"DOI": "10.1080/10915810290096513",
		"ISSN": "1091-5818",
		"journalAbbreviation": "Int J Toxicol",
		"language": "eng",
		"note": "PMID: 12396675",
		"page": "19-94",
		"source": "PubMed",
		"title": "Final report on the safety assessment of BHT(1)",
		"volume": "21 Suppl 2",
		"author": [
			{
				"family": "Lanigan",
				"given": "Rebecca S."
			},
			{
				"family": "Yamarik",
				"given": "Torill A."
			}
		],
		"issued": {
			"date-parts": [
				[
					"2002"
				]
			]
		}
	}
The outcome is [1]Rebecca S. Lanigan, Torill A. Yamarik. Final report on the safety assessment of BHT(1)[J/OL]. International Journal of Toxicology, 2002, 21 Suppl 2: 19-94. 
However, if I use Zotero to generate the bib and the rendered content is as follows, which is the same as the bibliograph from Google Scholar following the China GB 7714 standard.
[1]	LANIGAN R S, YAMARIK T A. Final report on the safety assessment of BHT(1)[J/OL]. International Journal of Toxicology, 2002, 21 Suppl 2: 19-94.
The issue is : 1. the family name should be capitalized; 2. the given name should be the capitalized initiate.

I also tried to replace the csl file in the Style-24.3.jar with the latest csl file from Zotero website https://www.zotero.org/styles?q=7714. But, it seems not working.

Could you please take a looking at it? Or anything wrong by myself? Many thanks!

**Comment by michel-kraemer** [comment]
Nice catch! This is indeed a bug. I've just fixed it and will release a new version soon.

**Comment by hongjingxu** [comment]
Nice to hear that and looking forward to a new version.

**Comment by michel-kraemer** [comment]
I've just released version 3.2.0.
