### ISSUE TITLE
Add markdown as output format

### ISSUE THREAD

**Issue by koppor** [michel-kraemer/citeproc-java#252]
Currently, the output formats include asciidoc, fo, html, and text (`de.undercouch.citeproc.CSL#setOutputFormat(java.lang.String)`. Markdown is missing.

Some users do want to have Markdown (https://github.com/JabRef/jabref/pull/12220).

Side comment: Would it be possible to generate links to DOIs when exporting to Markdown (refs https://github.com/michel-kraemer/citeproc-java/issues/97)?

**Comment by michel-kraemer** [comment]
Yes, this is a pretty good idea! I'll implement it in the next few days and get back to you.

**Comment by michel-kraemer** [comment]
I've just released version 3.2.0. You can now use the `markdown` output format (with some HTML tags, used sparingly) or the `markdown-pure` format (without any HTML tags at all, but lacking some formatting options).
