### ISSUE TITLE
CSLItemData field maps "eventplace" instead of "event-place" 

### ISSUE THREAD

**Issue by rptmat57** [michel-kraemer/citeproc-java#27]
Just like publisher-place, the place field for event should be "event-place".
However CSLItemData maps "eventplace" instead.

**Comment by rptmat57** [comment]
this is a copy-paste from ieee csl style where "event-place" is used.

    <macro name="event">
    <choose>
      <if type="paper-conference speech" match="any">
        <choose>
          
          <if variable="container-title">
            <group delimiter=", ">
              <group delimiter=" ">
                <text term="in"/>
                <text variable="container-title" font-style="italic"/>
              </group>
              <text variable="event-place"/>
            </group>
          </if>
          
          <else>
            <group delimiter=", ">
              <group delimiter=" ">
                <text term="presented at"/>
                <text variable="event"/>
              </group>
              <text variable="event-place"/>
            </group>
          </else>
        </choose>
      </if>
    </choose>
    </macro>

**Comment by michel-kraemer** [comment]
This has been fixed in bf6ef40d657f26d9b0df02824a44f8020e0cade4. Please use the latest snapshot 1.0.0-SNAPSHOT:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/1.0.0-SNAPSHOT/
