### ISSUE TITLE
Process fails on certain PDF files?

### ISSUE THREAD

**Issue by bhecht2** [michel-kraemer/citeproc-java#32]
Hi,

Trying to run siteproc against a specific PDF file, causes a crash to my machine.
Can you please verify this file works for you? I notice it is a power point file converted to PDF
[23847801770001241.pdf](https://github.com/michel-kraemer/citeproc-java/files/624829/23847801770001241.pdf)

The problematic process is the pdftoxml, when running against this file, the memory consumption rises until 100%, causing the machine to crash.

**Comment by michel-kraemer** [comment]
What do you mean by running citeproc-java against a PDF file? The tool does not support PDF files as input. Can you please send me the command line that you use or the API calls you're performing?

**Comment by bhecht2** [comment]
So sorry, wrong github source, please close and delete :)
thanks for the prompt response.
