### ISSUE TITLE
Cannot make citations for dependent styles

### ISSUE THREAD

**Issue by workspaceit** [michel-kraemer/citeproc-java#37]
I am using this code to make the citations and it works fine.
`String bibl = CSL.makeAdhocBibliography("chicago-author-date", item).makeString();`

But, how to make a citations that is dependent?
`String bibl = CSL.makeAdhocBibliography("dependent/water", item).makeString();`

It gives an error: java.lang.Boolean cannot be cast to java.util.List. Is there different a way to make citation for the dependent ones?

**Comment by michel-kraemer** [comment]
Dependent styles are not supported in the current version of citeproc-java. You can work around this by referring to the parent style instead. For `dependent/water` this would be `multidisciplinary-digital-publishing-institute`.

**Comment by michel-kraemer** [comment]
I fixed this in commit 224b2db and uploaded a new snapshot:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/1.1.0-SNAPSHOT/

I hope this helps!
