### ISSUE TITLE
Editors get listed twice

### ISSUE THREAD

**Issue by alinamx** [michel-kraemer/citeproc-java#38]
Im creating References in APA style. I just recognized that if there is one editor, it will be added twice, but the Ed. shortcut is correct.
Example:
Costantino, C. (2004). Three Essays on Vertical Product Differentiation: Exclusivity, Non-exclusivity and Advertising. (R. R. Betancourt, R. R. Betancourt, Ed.).

Not sure, if I'm doing something wrong, or if it is an error.
Tank you!

**Comment by michel-kraemer** [comment]
How are you creating your reference? Through the API or through the command-line interface? What kind of database are you using? BibTeX, JSON or something else? Can you post the database entry and/or the respective code snippet?

**Comment by alinamx** [comment]
I downloaded it with Maven, to use it in my project.
I'm using the bibtex converter, so loading from my .bib file.

This is an Example for the database entry:
`@book{EconBiz-10009450595,
title = {{Essays on the Role of Specific Human Capital}},
author = {Hu, Xiaohan},
editor = {Hellerstein, Judith},
year = {2007-06-04},
type= {Thesis},
language= {eng},
}`

This is the codesnippet dealing with it:
`BibTeXDatabase db = null;
        try {
            db = new BibTeXConverter().loadDatabase(new FileInputStream(path + file));
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ParseException e) {
            e.printStackTrace();
        }

        BibTeXItemDataProvider provider = new BibTeXItemDataProvider();
        provider.addDatabase(db);

        try {
            CSL citeproc = new CSL(provider, "apa");
            citeproc.setOutputFormat("text");
            provider.registerCitationItems(citeproc);
            Bibliography bibl = citeproc.makeBibliography();
            for (String entry : bibl.getEntries()) {
                entry = entry.replace("’", "'");
                entry = entry.replace(",", ",");
                //System.out.println(entry);
                Files.write(Paths.get(path + "\\finalTxtFiles\\bibliographyRef.txt"), entry.getBytes(), StandardOpenOption.APPEND);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
`

I just realized, that this happens always, no matter how many editors there are, the outputs will be like:
Pathomsiri, S. (2006). Assessment of Productive Efficiency of Airports. (A. Haghani, A. Haghani, Ed.).

shui,  haiyan. (2004). Time Inconsistency in the Credit Card Market. (L. M. Ausubel, J. Rust, & T. Test, L. M. Ausubel, J. Rust, & T. Test, Eds.).

**Comment by michel-kraemer** [comment]
OK. Thanks. I'll look into this and get back to you.

**Comment by michel-kraemer** [comment]
Thanks for reporting the issue. I fixed it and uploaded a new snapshot to Sonatype OSS.
