### ISSUE TITLE
Encoding of CSL definition (CSL definitions are read as non-Unicode)

### ISSUE THREAD

**Issue by ailintom** [michel-kraemer/citeproc-java#39]
Thank you for the great tool.
There is a problem with the encoding of the CSL definitions. When working with bibliographical input files in UTF-8 citeproc-java seems to still load CSL definitions in ANSI, and then uses these non-Unicode values in the output. Thus when processing a UTF-8-encoded json file with the command line 
`citeproc-java bibliography -i "sds.json" -s chicago-author-date -f html >1.htm`
the program outputs a html file, which has all the unicode characters of the input file preserved, but instead of the en-dash (U+2013) it uses the character 0x96, which corresponds to the ANSI code of the en-dash, but does not display correctly when the rest of the file is encoded in UTF-8.
The same goes for CSL definitions containing signs in non-Western languages (example: gost-r-7-0-5-2008): they are read in their respective non-Unicode codepage.

**Comment by michel-kraemer** [comment]
What version of citeproc-java are you using? Would it be possible to send me the input file `sds.json` maybe by email? This would make it easier to reproduce and fix the issue. Thanks!

**Comment by ailintom** [comment]
I am using 1.0.1 on Win 7 from command lines. I sent you the file by email; it is an export from Zotero (for test purposes; I intend to generate CSL JSON from my own application and process it with citeproc-java. (But the problem is not with the input file, for the data from the file is rendered correctly, the problem is with the signs defined by the CSL).

**Comment by michel-kraemer** [comment]
Thanks. I received the test file. I'll look into the issue and get back to you.

**Comment by StefanHagel** [comment]
What I seem to get here is not the ANSI equivalents but the codes of the correct UTF-8 encoding, themselves erroneously encoded in UTF-8 (similar to data imported from Zotero, #43).

**Comment by michel-kraemer** [comment]
@ailintom If the problem only occurs if you write to an output file using I/O redirection, the problem may also be related to your shell. Try to use the `-o` parameter to specify an output file. citeproc-java uses UTF-8 encoding when writing to output files.

**Comment by StefanHagel** [comment]
For me, it happens when calling via JVM. Unicode output is perfect for the content of bibliographical entries, but flawed for Unicode characters defined in the CSL stylesheet, such as typographical quotation marks or dashes.

**Comment by michel-kraemer** [comment]
@StefanHagel Oh, really? I need to check this. I'm reopening the issue.

**Comment by michel-kraemer** [comment]
@StefanHagel I can't reproduce this. Am I doing something wrong?

```java
@Test
public void unicodeQuotes() throws Exception {
    CSLItemData item = new CSLItemDataBuilder()
        .id("article1")
        .type(CSLType.ARTICLE)
        .title("My awesome article")
        .author(
            new CSLNameBuilder().given("Awesome").family("Author").build()
        )
        .issued(2018)
        .build();

    String bibl = CSL.makeAdhocBibliography("environment-and-urbanization.csl",
            "text", item).makeString();
    assertEquals("Author, Awesome (2018), \u201cMy Awesome Article\u201d.\n", bibl);
}
```

**Comment by StefanHagel** [comment]
Here's an output of `makeCitation` in `html `style (same for `text`) written to a text file. The Unicode in the title (i with macron in "Nid") is taken correctly from the dataset, even though the word has passed through capitalisation. The quotation marks, however, are "double-utf-8-ed":

> Hagel, Stefan (2005), âIs Nīd Qabli Dorian? Tuning and Modality in Greek and Hurrian Musicâ, <i>Baghdader Mitteilungen</i> Vol 36, pages 287–348.

[csl-QuotationMarks.txt](https://github.com/michel-kraemer/citeproc-java/files/2025441/csl-QuotationMarks.txt)

Can't run more extensive tests this week, sorry. I have never tested makeAdhocBibliography

**Comment by StefanHagel** [comment]
Entirely my mistake, sorry! I had passed not a stylesheet name but the contents of a stylesheet file, and the wrong conversion happened in this context. Issue can be closed, as far as I am concerned.
