### ISSUE TITLE
Bibtex month like #mar# not parsed

### ISSUE THREAD

**Issue by Siedlerchr** [michel-kraemer/citeproc-java#41]
Originally reported at https://github.com/JabRef/jabref/issues/3239
Enter the month 3 in the month field in JabRef.
JabRef converts the month to #mar# which is then passed to CSL.

I debugged a bit through and found that the toMonth method returns -1.
 You could take this as a chance to make use of the new fancy DateFormatter in Java 8 and simply the parsing of dates:
https://docs.oracle.com/javase/tutorial/datetime/iso/format.html

**Comment by michel-kraemer** [comment]
The issue in JabRef has been fixed. Is there still something that we need to do here on the side of citeproc-java? `DateParser` is already able to recognise `mar` as a month name.

By the way: the new `DateFormatter` was already available when I created citeproc-java. However, `DateParser` is even more lenient and specifically optimised for BibTeX.

**Comment by michel-kraemer** [comment]
I'm closing this due lack of response. Also, the issue seems to be fixed already. If there still is a problem please open a new issue. Thanks.
