### ISSUE TITLE
MemLeak in V8

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#45]
I'm experiencing an OOME when using v8. Inspecting the code I'm missing the code to dispose the callback methods from the `functionRegistry` in V8. Maybe I'm missing something? (I'm using the example code from https://michel-kraemer.github.io/citeproc-java/.) Is it possible to deregister the items?

Environment:
- linux 4.4.120-45-default x86_64
- java 8u161-oracle
- com.eclipsesource.j2v8:j2v8_linux_x86_64:4.8.0

Example code (run with -Xmx64m renders 1869 entries before terminating with OOME):
```
import de.undercouch.citeproc.CSL;
import de.undercouch.citeproc.csl.CSLItemData;
import de.undercouch.citeproc.csl.CSLItemDataBuilder;
import de.undercouch.citeproc.csl.CSLType;

import java.io.IOException;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        CSLItemData item;
        item = new CSLItemDataBuilder()
                .type(CSLType.WEBPAGE)
                .title("citeproc-java: A Citation Style Language (CSL) processor for Java")
                .author("Michel", "Krämer")
                .issued(2016, 11, 20)
                .URL("http://michel-kraemer.github.io/citeproc-java/")
                .accessed(2018, 4, 12)
                .build();

        try {
            System.out.println("Press enter to begin");
            scanner.nextLine();
            for (int i=1; i <= 3000; i++) {
                System.out.println("entry " + i + ":" + CSL.makeAdhocBibliography("ieee", item).makeString());
            }
            System.out.println("Press enter to end");
            scanner.nextLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

```

**Comment by gallardo** [comment]
I've tried a workaround: using (and reusing) `CSL.makeBibliography` instead of `makeAdhocBibliography` with a "faked" `ItemDataProvider` whose `retrieveItem` is overriden to return the item of my choose. It works apparently very well, but I'm a bit sceptical, as it doesn't look as the native way of doing it...

Does it sound sensible?

**Comment by michel-kraemer** [comment]
`CSL.makeBibliography` should be the preferred way anyhow if you need to create bibliographies over and over again. `makeAdhocBibliography` is just too slow for that purpose.

However, it seems you found a bug. I do not have the time to look into it now or in the next couple of days, but I will get back to you as soon as I can. Since you already identified the root of the problem - if you like, you can send me a pull request in the meantime.

**Comment by gallardo** [comment]
I would need to study the code carefully before opening a PR. This would take a while. I cannot guarantee that I'll find the time myself either.
