### ISSUE TITLE
Importing items from Mendeley fails

### ISSUE THREAD

**Issue by StefanHagel** [michel-kraemer/citeproc-java#46]
While importing using the Zotero remote connector works (except for the unicode issue reported in #43, importing from Mendelay fails both from citeproc-java.bat and when using a JVM.
After authorizing, when executing

`citeproc-java mendeley list`

I get:

> Retrieving items ...Exception in thread "main" java.lang.NullPointerException
>         at de.undercouch.citeproc.mendeley.MendeleyConnector.getItemIDs(Mendeley
> Connector.java:164)
>         at de.undercouch.citeproc.remote.RemoteConnectorAdapter.getItemIDs(Remot
> eConnectorAdapter.java:69)
>         at de.undercouch.citeproc.remote.RemoteConnectorAdapter.getItemIDs(Remot
> eConnectorAdapter.java:69)
>         at de.undercouch.citeproc.helper.tool.CachingRemoteConnector.getItemIDs(
> CachingRemoteConnector.java:107)
>         at de.undercouch.citeproc.tool.AbstractRemoteCommand.connect(AbstractRem
> oteCommand.java:139)
>         at de.undercouch.citeproc.tool.AbstractRemoteCommand.doRun(AbstractRemot
> eCommand.java:79)
>         at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToo
> lCommand.java:113)
>         at de.undercouch.citeproc.CSLTool.doRun(CSLTool.java:170)
>         at de.undercouch.citeproc.tool.AbstractCSLToolCommand.run(AbstractCSLToo
> lCommand.java:113)
>         at de.undercouch.citeproc.CSLTool.main(CSLTool.java:132)

This seems to indicate that `response.getHeaders(LINK);` returns NULL in some circumstances? In that case, should one test against NULL here?

**Comment by michel-kraemer** [comment]
What happens from time to time is that Mendeley changes its API and citeproc-java needs to be updated. Since I'm not always as fast as Mendeley, I was already thinking about removing the remote connectors for Zotero and Mendeley in order to reduce maintenance effort, thinking that the connectors are probably not used in practise anyhow. So, I would be interested in your use case. Why are you using the Zotero and Mendeley connectors and do you really need them?

**Comment by StefanHagel** [comment]
I  am considering basing the bibliographical tools of [Classical Text Editor ](http://cte.oeaw.ac.at)10 on citeproc-java, and here the remote connectors are quite handy (with local caching). Otherwise I would probably need to replicate their functionality in Pascal.

**Comment by michel-kraemer** [comment]
Thanks. I just fixed the `NullPointerException`
