### ISSUE TITLE
Unicode in Zotero-imported strings is doubly-encoded utf-8

### ISSUE THREAD

**Issue by StefanHagel** [michel-kraemer/citeproc-java#51]
I am returning to an issue I have raised earlier and could not find a solution for.
It concerns Unicode in items that are retrieved from Zotero. Characters above #127 are not encoded correctly as utf-8, but as an utf-8 encoding of the individual byte components of the correct utf-8 characters. In this way, a character that would normally be encoded with 2 bits has 4 bits (see example below).

In most but not all cases, this can be reverted by converting the strings from utf-8, taking the result as consisting of 8-bit characters once more forming utf-8. However, even this is bound to fail in certain cases, making the regular Zotero import basically unusable for working with literature other than English (and Latin).

The issue is easily reproduced using `citeproc-java.bat` to generate a bibliography from Zotero, e.g.:
`.\citeproc-java.bat --output "bib.txt" zotero bibliography `
Any accented vowel or German Umlaut is concerned, as are entries containing Greek, Arabic etc.

For instance, one of my entries reads in notpad++, which correctly interprets the file as utf-8:

> [19]E. PÃ¶hlmann, DenkmÃ¤ler altgriechischer Musik: Sammlung, Ãœbertragung und ErlÃ¤uterung aller Fragmente und FÃ¤lschungen. NÃ¼rnberg: Carl, 1970.

while it should read:

[19]E. Pöhlmann, Denkmäler altgriechischer Musik: Sammlung, Übertragung und Erläuterung aller Fragmente und Fälschungen. Nürnberg: Carl, 1970.

On closer inspection (e.g. changing the display mode from utf-8 to Ansi, or using a hex editor), the entry actually reads like this:

> [19]E. PÃƒÂ¶hlmann, DenkmÃƒÂ¤ler altgriechischer Musik: Sammlung, ÃƒÅ“bertragung und ErlÃƒÂ¤uterung aller Fragmente und FÃƒÂ¤lschungen. NÃƒÂ¼rnberg: Carl, 1970.

So far I have no idea where this double-encoding may happen...

All best,
Stefan

PS: I should add that this does *not* concern Unicode characters that are part of the csl style - only text imported from Zotero.

**Comment by michel-kraemer** [comment]
I suppose this is fixed with #52. If not, just let me know.

**Comment by StefanHagel** [comment]
Yes, I hope this fixed it. Thanks for merging!
