### ISSUE TITLE
Issues with code in Java 10

### ISSUE THREAD

**Issue by YashchukM** [michel-kraemer/citeproc-java#53]
Hello Michael,

The provided sample code generates a string of kind **null312.** , when running with Java 10.

Few details:
- The issue is not reproducible on Java 8;
- The issue appears only on the first run of _CSL.makeBibliography()_ method, all subsequent calls work fine;
- Specific version: **Java 10.0.2+13**, OS: **Mac OS**.

Although I am pretty sure that the problem is connected with Java 10 changes, will highly appreciate your help. Thanks in advance!

```import java.io.IOException;

import de.undercouch.citeproc.CSL;
import de.undercouch.citeproc.ItemDataProvider;
import de.undercouch.citeproc.csl.CSLItemData;
import de.undercouch.citeproc.csl.CSLItemDataBuilder;
import de.undercouch.citeproc.csl.CSLType;

public class BibliographyFailure {
    public static final String ID = "0";

    public static void main(String[] args) throws IOException {
        CSL formatter = getCSL();

        String bibliography = formatter.makeBibliography().makeString();

        System.out.println(bibliography);
    }

    private static CSL getCSL() throws IOException {
        SingleItemDataProvider provider = new SingleItemDataProvider();
        CSLItemDataBuilder itemBuilder = new CSLItemDataBuilder()
                .id(ID)
                .type(CSLType.ARTICLE_MAGAZINE)
                .abstrct("Some abstract")
                .title("Some title")
                .publisher("Some Cool Publisher Limited")
                .ISSN("12345678")
                .containerTitle("Cont Title")
                .journalAbbreviation("MYCM")
                .source("Magazines")
                .page("312")
                .pageFirst("312");
        provider.setItem(itemBuilder.build());

        CSL formatter = new CSL(provider, "mla");
        formatter.setOutputFormat("text");
        formatter.registerCitationItems(ID);
        return formatter;
    }

    private static class SingleItemDataProvider implements ItemDataProvider {
        private CSLItemData item;

        public void setItem(CSLItemData item) {
            this.item = item;
        }

        @Override
        public CSLItemData retrieveItem(String id) {
            return item;
        }

        @Override
        public String[] getIds() {
            return new String[]{item.getId()};
        }
    }
}
```

**Comment by meier-rene** [comment]
I can confirm this issue on linux.
```
java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```
As a workaround I'm calling the CSL.makeBibliography() twice atm.

**Comment by fluetze** [comment]
Same for me with Java 11. Sometimes, makeBibliography() will return correct results at the first run, but in most cases it must be called twice to get proper results.

**Comment by michel-kraemer** [comment]
Thanks for reporting. I just pushed a patch that uses Graal JavaScript on Java 11 or higher, which resolves this issue.

**Comment by fluetze** [comment]
Thank you. Will you publish a new version on maven central?

**Comment by michel-kraemer** [comment]
Sure, I will. But there are a couple of other things I'd like to do first. Would a snapshot also work for you?

**Comment by fluetze** [comment]
Yes! Thx!

**Comment by michel-kraemer** [comment]
I just uploaded a snapshot to https://oss.sonatype.org/content/repositories/snapshots. The new version number is 2.0.0-SNAPSHOT.

See:
https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/2.0.0-SNAPSHOT/

**Comment by fluetze** [comment]
The snapshot works for me and solves the issue, but I had to add two additional dependencies,

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.9</version>
      <scope>runtime</scope>
    </dependency>

(for the Java version test in ScriptRunnerFactory.java)

and

    <dependency>
      <groupId>org.jbibtex</groupId>
      <artifactId>jbibtex</artifactId>
      <version>1.0.17</version>
    </dependency>

(to use the BibTeXItemDataProvider)

**Comment by michel-kraemer** [comment]
@fluetze Ah, that's good to know. I just fixed that. It should not be necessary anymore with the latest snapshot.
