### ISSUE TITLE
ThreadLocal issue

### ISSUE THREAD

**Issue by benoitcoppens** [michel-kraemer/citeproc-java#54]
Hi,
I'm using citeproc-java in a Tomcat web app and it works fine until I shutdown my Tomcat. At that time, I get the following error message in the logs:

15-Nov-2018 13:42:04.296 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [MyApp] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@164ff66]) and a value of type [de.undercouch.citeproc.script.JREScriptRunner] (value [de.undercouch.citeproc.script.JREScriptRunner@13558c8]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Any idea?

Thanks,
Benoit

**Comment by michel-kraemer** [comment]
Thanks for reporting this. I just pushed a patch that adds a `removeThreadLocals()` method to the `CSL` class. Add a `ServletContextListener` to your web application and call this new method when Tomcat destroys the context.

**Comment by benoitcoppens** [comment]
Thanks! Is it planned to release a new version of the library including this fix?

**Comment by michel-kraemer** [comment]
Yes. I'm currently working on it but it may take a couple of days/weeks due to lack of time. I hope this is OK. I can publish a snapshot at any time if you wish.

**Comment by benoitcoppens** [comment]
I can wait a new release - no worries. Thanks a lot!

**Comment by michel-kraemer** [comment]
@benoitcoppens I just released version 2.0.0

**Comment by benoitcoppens** [comment]
Thanks a lot!
