### ISSUE TITLE
BibTeXItemDataProviderTest broken: rendered wrong abbreviation ('ed' instead of 'Ed')

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#58]
(This seems to be provoked by an update in the APA csl.)

I have tried updating the expected text with the output from Zotero, but the test still outputs '_**e**d._' instead of '_**E**d._'. According to https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/apa_abbreviations.html, `ed.` means 'edition' while `Ed.` means Editor.

### Expected
Hu, X. (2007). Essays on the Role of Specific Human Capital (J. Hellerstein, Ed.).

### Actual
Hu, X. (2007). Essays on the Role of Specific Human Capital (J. Hellerstein, **e**d.).

**Comment by gallardo** [comment]
The test passes again with https://github.com/michel-kraemer/citeproc-java/pull/56.

**Comment by michel-kraemer** [comment]
Thanks for spotting this!
