### ISSUE TITLE
BibTeXItemDataProviderTest broken: two instead one citations

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#59]
Upgrading citeproc-js to https://github.com/Juris-M/citeproc-js/releases/tag/1.1.215 breaks `de.undercouch.citeproc.bibtex.BibTeXItemDataProviderTest.numericAlphabetical` in https://github.com/michel-kraemer/citeproc-java/blob/88f0ba5d58cf1c81f18688e8f599badd18c03f3b/citeproc-java/src/test/java/de/undercouch/citeproc/bibtex/BibTeXItemDataProviderTest.java#L127-L128 when citing entry `Anonymous:1990:DMR`: the second invokation produces two citations instead of one.

The problem could be have been introduced upstream.

(N.B.: The test would be more valuable if it wouldn't pick random entries. Randomness hinders tests reproducibility.)

**Comment by michel-kraemer** [comment]
For the time being, I made the test reproducible so the CI can run through, but I'll leave this open because we need to investigate the root cause.

**Comment by michel-kraemer** [comment]
I debugged the code and everything works as expected. The unit test just doesn't handle the result of `makeCitation` correctly. I'll push a fix now.
