### ISSUE TITLE
Fix doc: installDist vs installApp

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#61]
Documentation at https://michel-kraemer.github.io/citeproc-java/using/building/ is incorrect. (I cannot find the sources to file a PR.) The current command to build  `citeproc-java-tool` is apparently:

    $ ./gradlew installDist

**Comment by michel-kraemer** [comment]
Thanks for reporting but the website is still valid for the current release. I'll update it once I release 2.0.0.
