### ISSUE TITLE
Dissertations incorrectly rendered: genre not set when importing BibTeX

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#62]
Dissertation entries are rendered incorrectly:

#### Expected (emphasis mine)
Wagener, K. C. (2003). Factors Influencing Sentence Intelligibility in Noise (**Dissertation**, University of Oldenburg). Retrieved from http://docserver.bis.uni-oldenburg.de/publikationen/dissertation/2003/wagfac03/wagfac03.html

#### Actual
Wagener, K. C. (2003). Factors Influencing Sentence Intelligibility in Noise (University of Oldenburg). Retrieved from http://docserver.bis.uni-oldenburg.de/publikationen/dissertation/2003/wagfac03/wagfac03.html

#### Notes
The entry is rendered correctly when imported from CSL-JSON.

#### Sources

As sources, I have imported in Zotero an exemplary bibtex entry from http://medi.uni-oldenburg.de/html/DissertationBibFiles/dissertation.html and exported to bibtex and CSL/JSON:

##### bibtex

```
@phdthesis{
		Type = {dissertation},
		Title = {Factors Influencing Sentence Intelligibility in Noise},
		Author = {Kirsten C. Wagener},
		School = {University of Oldenburg},
		URL = {http://docserver.bis.uni-oldenburg.de/publikationen/dissertation/2003/wagfac03/wagfac03.html},
		Year = {2003},
}

```

##### CSL/JSON

```
{
	"id": "http://zotero.org/users/local/xesCO2jf/items/EZXMZ8B6",
	"type": "thesis",
	"title": "Factors Influencing Sentence Intelligibility in Noise",
	"publisher": "University of Oldenburg",
	"genre": "dissertation",
	"URL": "http://docserver.bis.uni-oldenburg.de/publikationen/dissertation/2003/wagfac03/wagfac03.html",
	"author": [
		{
			"family": "Wagener",
			"given": "Kirsten C."
		}
	],
	"issued": {
		"date-parts": [
			[
				"2003"
			]
		]
	}
}

```

#### Analysis

From [the CSL-specification](http://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables), the CSL-field `genre` seems to be the most appropriate to set the type of thesis (e.g. _PhD dissertation_), and is the one that the [APA template](https://github.com/citation-style-language/styles/blob/master/apa.csl) reads for this purpose. This field is set when importing entries from CSL-JSON (as Zotero does: https://aurimasv.github.io/z2csl/typeMap.xml#map-thesis), but not when importing entries from bibtex.

Regarding BibTeX, I could find that the `field` type be used for _"the type of publication, if needed. For thesis, for instance, in order to distinguish between a masters thesis and a PhD"_ ([Tame the BeaST  --  The B to X of BibTeX](http://mirrors.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf)).

biblatex and BibTeXML do also document this use:

- The entry type `phdthesis` is used for PhD thesis and takes an optional field `type` to _call your reference a 'Ph.D. dissertation' instead of the default 'PhD thesis'_ ([the content model in bibtexml](http://bibtexml.sourceforge.net/btxdoc.pdf)).

- The entry type `phdthesis` takes the optional field `type` to specify the type of thesis ([biblatex documentation, §2.1.1 ](http://mirror.ox.ac.uk/sites/ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf).

The [current documented mapping](https://www.scss.tcd.ie/joeran.beel/blog/2012/08/08/docear4word-mapping-bibtex-fields-and-types-with-the-citation-style-language/) does unfortunately leave the field `genre` unassigned.

**Comment by michel-kraemer** [comment]
Very thorough analysis. Thank you so much!
