### ISSUE TITLE
Order of BibTeXDatabase gets lost in BibTeXConverter

### ISSUE THREAD

**Issue by borkdude** [michel-kraemer/citeproc-java#64]
On this line:

https://github.com/michel-kraemer/citeproc-java/blob/1d5bf0e7bbb2bdc47309530babf0ecaba838bf10/citeproc-java/src/main/java/de/undercouch/citeproc/bibtex/BibTeXConverter.java#L163

the order of the `BibTeXDatabase` gets lost while transforming it to a `Map<String, CSLItemData>`. Elsewhere in the code a `LinkedHashMap` is used to prevent this (e.g. [here](https://github.com/michel-kraemer/citeproc-java/blob/1d5bf0e7bbb2bdc47309530babf0ecaba838bf10/citeproc-java/src/main/java/de/undercouch/citeproc/ListItemDataProvider.java#L32)). 

That might be a good choice here as well. I had to work around this API to preserve this order.

**Comment by michel-kraemer** [comment]
Thanks for spotting this!
