### ISSUE TITLE
Broken test techReportWithExplicitType

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#67]
This is accidentally introduced in commit https://github.com/michel-kraemer/citeproc-java/pull/69/commits/80c46a30a3288b10bb25e9e2dd6f8fa62bab3949. The PR https://github.com/michel-kraemer/citeproc-java/pull/69 already contains the fix and could be squashed.

**Comment by gallardo** [comment]
I cannot reproduce this yet merging from yesterday's master.

**Comment by michel-kraemer** [comment]
Can this be closed?

**Comment by gallardo** [comment]
I cannot reproduce it.
