### ISSUE TITLE
Incorrect DIN 1505 rendering due to booktitle mapping

### ISSUE THREAD

**Issue by gallardo** [michel-kraemer/citeproc-java#78]
[BibTeXConverter](https://github.com/michel-kraemer/citeproc-java/blob/b9c08fe5684a64bec420adbc6b74644728f5068b/citeproc-java/src/main/java/de/undercouch/citeproc/bibtex/BibTeXConverter.java) currently maps `booktitle` to `collection-title` and to `container-title`. When using [din 1505-2](https://github.com/citation-style-language/styles/blob/c0e46307dcdaf8172e54998d96a4b1bcce381833/din-1505-2.csl) to render publications, this results in a duplicated title.

The source for the bibtex -> CSL mapping is docear, but unfortunately docear has been discontinued. @michel-kraemer Do you think it's possible to change this mapping, so that only `container-title` is filled? (This also raises the question about how to maintain and document the mapping.)

# Current result
<sub>Edition note: line breaks introduced for web readability</sub>
```
$ cat ~/Downloads/Publication-RUS-10489339.bib 
@inproceedings{reichel_importance_2019,
	address = {Stuttgart},
	title = {The {Importance} of {Appropriate} {Systems} and {Software} {Engineering} for {Avionics} {Systems} from the {Academic} {Perspective}},
	booktitle = {1st {Workshop} on {Software} {Engineering} for {Avionics} {Systems} ({AVIOSE}19)},
	author = {Reichel, Reinhard},
	month = feb,
	year = {2019},
	keywords = {ils}
}

$ bin/citeproc-java bibliography -i publication.bib -s din-1505-2 -f text
Reichel, Reinhard: The Importance of Appropriate Systems and Software
 Engineering for Avionics Systems from the Academic Perspective. In: 1st
 Workshop on Software Engineering for Avionics Systems (AVIOSE19), 1st
 Workshop on Software Engineering for Avionics Systems (AVIOSE19).
 Stuttgart, 2019

```
# Expected result
<sub>Edition note: line breaks introduced for web readability</sub>
```
$ cat publication.json
[
	{
		"id": "http://zotero.org/users/local/xesCO2jf/items/G5S9EFUI",
		"type": "paper-conference",
		"title": "The Importance of Appropriate Systems and Software Engineering for Avionics Systems from the Academic Perspective",
		"container-title": "1st Workshop on Software Engineering for Avionics Systems (AVIOSE19)",
		"publisher-place": "Stuttgart",
		"event-place": "Stuttgart",
		"author": [
			{
				"family": "Reichel",
				"given": "Reinhard"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2019",
					2
				]
			]
		}
	}
]

$ bin/citeproc-java bibliography -i publication.json -s din-1505-2 -f text
Reichel, Reinhard: The Importance of Appropriate Systems and Software
 Engineering for Avionics Systems from the Academic Perspective. In: 1st
 Workshop on Software Engineering for Avionics Systems (AVIOSE19).
 Stuttgart, 2019
```
# Quick CSL analysis

`din-1505-2` renders both container-title and collection title of `paper-conference`:

![image](https://user-images.githubusercontent.com/790448/68945889-c9889a00-07b1-11ea-9e1e-ccb4a20a6b04.png)

**Comment by gallardo** [comment]
I have the same problem with `chicago-author-date.csl`:

![image](https://user-images.githubusercontent.com/790448/68951213-e6c36580-07bd-11ea-9d58-2c6f5eab5906.png)

**Comment by michel-kraemer** [comment]
@gallardo I'm not sure we can do this. If I remove the mapping to `collection-title`, the IEEE style does not work correctly anymore. This unit test fails: https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/test/java/de/undercouch/citeproc/bibtex/BibTeXItemDataProviderTest.java#L141-L171

In other words, the BibTeX entry

```bibtex
@inproceedings{ICIP99inv,
  author = "M.G. Strintzis and I. Kompatsiaris",
  title = "{3D Model-Based Segmentation of Videoconference Image Sequences}",
  booktitle = "IEEE International Conference on Image Processing (ICIP)",
  address = "Kobe, Japan",
  month = "October 25-28",
  year = "1999",
  note = {invited paper},
  pages = ""
}
```

with IEEE style will render to

    [1]M. G. Strintzis and I. Kompatsiaris, “3D Model-Based Segmentation of Videoconference Image Sequences,” Kobe, Japan, 1999.

instead of 

    [1]M. G. Strintzis and I. Kompatsiaris, “3D Model-Based Segmentation of Videoconference Image Sequences,” in IEEE International Conference on Image Processing (ICIP), Kobe, Japan, 1999.

`booktitle` is missing.

It seems, we have a deadlock here. I'm open for ideas.

**Comment by gallardo** [comment]
:confounded:Thanks for your analysis. I didn't realize that. Unfortunately, I'm not an style expert and cannot propose a fix at the moment.
