### ISSUE TITLE
Citation style discrepancies between JabRef and Zotero

### ISSUE THREAD

**Issue by barinovdesign** [michel-kraemer/citeproc-java#87]
Hello,

I just wanted to report that I noticed some discrepancies in citation formatting when comparing the output of JabRef with that of Zotero. A JabRef forum member suggested that I open an issue here. Here is the [link](https://discourse.jabref.org/t/citation-styles-not-being-respected/2078) to our conversation on the forum.

--- 

The citations were created from the same base `.bib` file:

```bibtex
@book{travis_think_2019,
	title = {Think like a {UX} researcher: {How} to observe users, influence design, and shape business strategy},
	isbn = {978-1-138-36529-2},
	shorttitle = {Think like a {UX} researcher},
	language = {English},
	publisher = {CRC Press},
	author = {Travis, David and Hodgson, Philip},
	year = {2019},
	keywords = {user-experience, research}
}
```
**Output from JabRef (APA 7th ed.)**
> Travis, D., & Hodgson, P. (2019). Think like a UX researcher: How to observe users, influence design, and shape business strategy. CRC Press.

**Output from Zotero (APA 7th ed.)**
> Travis, D., & Hodgson, P. (2019). *Think like a UX researcher: How to observe users, influence design, and shape business strategy*. CRC Press.

Note how the title is not italicized in JabRef.

---

**Output from JabRef (MLA 8th ed.)**
> Travis, D., and P. Hodgson. *Think like a UX researcher: How to observe users, influence design, and shape business strategy*. CRC Press, 2019.

**Output from Zotero (MLA 8th ed.)**
> Travis, David, and Philip Hodgson. *Think like a UX Researcher: How to Observe Users, Influence Design, and Shape Business Strategy*. CRC Press, 2019.

Note how the authors are formatted differently, and how JabRef does not use title case as per the MLA guidelines.

---

Do you know what could be causing this? Please let me know if you need any additional information. Thank you.

**Comment by michel-kraemer** [comment]
Thanks for reporting these issues. I fixed them and published a new snapshot.
