### ISSUE TITLE
Hebrew terms support.

### ISSUE THREAD

**Issue by PrimoQA** [michel-kraemer/citeproc-java#90]
Hello, thank you very much for the great API and the assistance.
We would like to ask if it is possible to support some terms in the [Hebrew locale xml](https://github.com/citation-style-language/locales/blob/master/locales-he-IL.xml):

1.  We see that the et-al term is written as "et-al" in the xml: _term name="et-al" ואחרים /term_
And in our records we use id as "et al." , can you please add support for this form?
2. Same in: term name="and" ו /term
can you please add the same term with "&"? term name="&" ו /term.
3. Can you please also support the terms:
- anon
- print
- n.d.
- Web
- In
- pp

Thanks in advance.

**Comment by michel-kraemer** [comment]
This seems to be a duplicate of #93. Can you please confirm?
