### ISSUE TITLE
Using Java 14

### ISSUE THREAD

**Issue by bennyboer** [michel-kraemer/citeproc-java#91]
Hi guys!

I've been struggling a bit using citeproc-java with Gradle 6.4.1 and Java 14.
Nevertheless I got it to work using the following `build.gradle` and `module-info.java` snippets:

```groovy
plugins {
    id 'java'
    id 'de.jjohannes.extra-java-module-info' version '0.1'
}

dependencies {
    // ...

    implementation group: 'de.undercouch', name: 'citeproc-java', version: '2.0.0'
    runtimeOnly group: 'org.citationstyles', name: 'styles', version: '2.0.0'
    runtimeOnly group: 'org.citationstyles', name: 'locales', version: '2.0.0'
}

java {
    modularity.inferModulePath = true
}

extraJavaModuleInfo {
    automaticModule('citeproc-java-2.0.0.jar', 'de.undercouch.citeproc')
    automaticModule('jbibtex-1.0.17.jar', 'org.jbibtex')
    automaticModule('icu4j-62.1.jar', 'com.ibm.icu')
}
```

```java
module my.fancy.module {
    // ...

    requires de.undercouch.citeproc;
}
```

Anyone got a better way of doing this? It is pretty clean anyway so I don't really mind. But it would work way better (without the plugin) when there was another attribute `Automatic-Module-Name` in the manifest of the jar published to maven central:

```java
Manifest-Version: 1.0
Automatic-Module-Name: de.undercouch.citeproc
```

**Comment by Siedlerchr** [comment]
Hi, for us it works: ` implementation 'de.undercouch:citeproc-java:2.1.0-SNAPSHOT'`

**Comment by michel-kraemer** [comment]
@bennyboer If you like you may also try the latest development version:
https://oss.sonatype.org/content/groups/public/de/undercouch/citeproc-java/3.0.0-SNAPSHOT/

The new version provides a pure-Java CSL processor and does not require GraalVM or any other JavaScript runtime anymore.  This should make dependency management a lot easier.

Note that the snapshot does not provide all features of the previous implementation yet, but this applies to features that are rarely used anyway. The snapshot is quite stable already.

**Comment by bennyboer** [comment]
@michel-kraemer Well that is great news, thanks for letting me know! I will try it ASAP!

**Comment by michel-kraemer** [comment]
Cool! Let me know if you have any problems. Otherwise, please close the issue. Thanks!

**Comment by Siedlerchr** [comment]
So far in JabRef we didn't encounter any problems so far.
