### ISSUE TITLE
APA style, Article.number (.number(int)) added twice when no pages information

### ISSUE THREAD

**Issue by michael-goltsman** [michel-kraemer/citeproc-java#96]
For APA style, when no spage/epage/pages information provided along with 'number' - article number - article number appear in citation twice:
 coca cola, T. V. (2015). test journal article 20210131-1 **(No. 555). Article 555.** https://doi.org/10.777/data.006137****

Same citation when pages information exist:
coca cola, T. V. (2015). test journal article 20210131-1 **(No. 555).** 1–111. https://doi.org/10.777/data.006137

Regards

**Comment by michel-kraemer** [comment]
Can you please send me the citation data (in JSON) and/or maybe the code you're using to create the citation so I can reproduce the issue? Thanks.
