### ISSUE TITLE
DOI is prepended with 'https://doi.org/'

### ISSUE THREAD

**Issue by michael-goltsman** [michel-kraemer/citeproc-java#97]
DOI is automatically prepended with 'https://doi.org/' - is there a way to cancel this functionality and use DOI as identifier only?

Regards

**Comment by michel-kraemer** [comment]
Yes, you can disable link conversion by calling `CSL.setConvertLinks(false)`. Alternatively, if you're already using the latest snapshot version of citeproc-java (or 3.0.0-alpha.1) and want to disable link conversion for DOIs but still enable it for all other URLs, you can override `BaseFormat.addDOIPrefix` and then call `CSL.setOutputFormat()` to enable your custom format.
