### ISSUE TITLE
RIS Converter/Library Not Working

### ISSUE THREAD

**Issue by tschiet** [michel-kraemer/citeproc-java#98]
I followed the code on the website, but when I run it I get an error: _Caused by: java.lang.IllegalArgumentException: Could not make bibliography_

Here's what I have in my program:

        RISConverter risConverter = new RISConverter();
        RISLibrary lib = risConverter.loadLibrary(new FileInputStream(fileName));
        RISItemDataProvider provider = new RISItemDataProvider();
        provider.addLibrary(lib);

        CSL citeproc = new CSL(provider,"ieee");
        citeproc.setOutputFormat("text");
        provider.registerCitationItems(citeproc); 

        Bibliography bibl = citeproc.makeBibliography();

If I comment out "provider.registerCitationItems(citeproc); " then the bibliography object is empty. The library size is 1, so I know that there is an item that has been read in from the RIS file. But for some reason, the items are not moved from the library into the bibliography.

**Comment by michel-kraemer** [comment]
The code looks generally correct. It's hard to say what's happening here without more information. Do you have the full stack trace of the exception you're getting? Maybe you can also send me the RIS file so I can reproduce the issue?

**Comment by tschiet** [comment]
[ScienceDirect_citations_1611941082022 copy.ris.zip](https://github.com/michel-kraemer/citeproc-java/files/6128230/ScienceDirect_citations_1611941082022.copy.ris.zip)
![Screen Shot 2021-03-12 at 7 22 32 AM](https://user-images.githubusercontent.com/34183715/110906440-91279c00-82d1-11eb-9663-d31e30018f21.png)

Attached are the RIS file and a screen shot of the error I received.

**Comment by michel-kraemer** [comment]
Thanks for reporting! It seems citeproc-java is not able to RIS entries without an ID. I will fix this issue. You can work around it by adding an ID manually: just insert the line `ID  - yourid` after `TY  - JOUR`:

```
TY  - JOUR
ID  - yourid
T1  - Electrochemical switching in solid oxide cells at St Andrews
JO  - Fuel Cells Bulletin
...
```

**Comment by michel-kraemer** [comment]
It seems the issue has already been fixed in the lastest alpha version. If you like you can update your dependency to 3.0.0-alpha.1.
