### ISSUE TITLE
Superscript formatting in pure Java snapshot

### ISSUE THREAD

**Issue by tweverett** [michel-kraemer/citeproc-java#99]
I'm using the pure Java snapshot, which is excellent, so thank you! I extended BaseFormat to make a format for rtf and noticed that superscript formatting for citations doesn't seem to work. The openVerticalAlign and closeVerticalAlign methods are never called. Would you be able to point me in the right direction to make this work? E.g. style: vancouver-superscript.

**Comment by michel-kraemer** [comment]
Thanks for reporting! I fixed the issue and uploaded a new snapshot. Let me know if the problem persists.
